In [316]:
import pandas as pd
df = pd.read_csv('Telco.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [5]:
df["Churn"].value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

1) EDA Summary (insights + target understanding)

A short summary (5–8 lines):
What the dataset is about
What the target is
3 issues you already suspect
  

  The data pertains to the customers of a telecommunications company and includes demographic details, shared services (internet, telephone), and financial contract details,target is the Churn column (Did the customer leave the company or not?).
  issues I suspect :
  1- Because the data type in TotalCharges is Object, there are values ​​that are empty spaces that are counted as non-Nan when they are actually empty.
  2- There are values ​​labeled "No internet service" in the service columns; these cause problems in analysis. It's best to simply count them as "No" and be done with it.
  3- SeniorCitizen column must be object not number

In [ ]:
seniorCitizen = df[["SeniorCitizen"]]
seniorCitizen.describe()
seniorCitizen.value_counts()

       SeniorCitizen
count    7043.000000
mean        0.162147
std         0.368612
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max         1.000000

In [141]:
df["TotalCharges"].describe()

count     7043
unique    6531
top
freq        11
Name: TotalCharges, dtype: object

2) Cleaning Log (table)
column          current type      correct type
SeniorCitizen	Int64 (0/1)	    Category/Boolean	      (yes,no)تمثل صفة وليست رقماً حسابياً
TotalCharges	Object	         Float64	            يمثل مبالغ مالية ويجب إجراء عمليات حسابية عليه

In [317]:
df["TotalCharges"].describe()
subset = df[["tenure", "TotalCharges"]]
df_zero_tenure = subset[(df["tenure"] == 0)]
df_zero_tenure

      tenure TotalCharges
488        0
753        0
936        0
1082       0
1340       0
3331       0
3826       0
4380       0
5218       0
6670       0
6754       0

In [318]:
df["customerID"].duplicated().any()

False

Phase 3 — Data Quality Check (Before Cleaning)
Tasks
Investigate:
Missing values (count + percentage)
- Duplicates (customerID duplicates?)
 No 
 df["customerID"].duplicated().any()
 return false
 
- Invalid values (examples: empty strings, spaces, weird categories)
Outliers (MonthlyCharges, TotalCharges)
Deliverable
Write findings in this format:
Problem → Evidence → Impact

Problem 1:
There are empty spaces in some values ​​in the "TotalCharges" column.
Evidence:
When performing a group by pie for the TotalCharges of subscribers whose  "tenure equal zero, empty values ​​appear.
Impact:
Calculations fail (such as the average when I try to describe it).

Problem 2:
The "TotalCharges" column is defined as an Object (Text) instead of a Float.
Evidence:
the column contains decimal numbers, but the system reads them as text 
Impact → Inability to perform statistical analysis or calculate 

Problem 3:
Redundant categories such as "No internet service" and "No phone service".
Evidence → In columns such as OnlineSecurity or MultipleLines.
Impact → Data distraction (noise) leading to incorrect analysis.


Problem 4:
The "SeniorCitizen" column is stored as an int64 (0 and 1)
Evidence → It appears in the data as numbers, which may cause analysis programs to treat it as a numerical quantity.
Impact → It misleads descriptive analysis

Phase 4 — Data Cleaning (Execute + Explain)

Goal

Fix the dataset so it becomes consistent and usable.

Tasks (must be done)

Fix data types

Convert TotalCharges into numeric
Convert SeniorCitizen from binary (0/1) to object Category

In [319]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [320]:
df["SeniorCitizen"] = df["SeniorCitizen"].replace({1: "Yes", 0: "No"})
df.info()
df["SeniorCitizen"].value_counts()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   object
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(1), object(18)
memory usage: 1.1+ MB

SeniorCitizen
No     5901
Yes    1142
Name: count, dtype: int64

2)Handle missing values

Identify why values are missing (example: TotalCharges missing when tenure is 0)
  Because he is a new user and has not yet made any payments.
Choose a strategy:
drop rows (only if very small)
fill with median/0 (only if justified)

i will fill with zero   Because he is a new user and has not yet made any payments.

In [321]:
df["TotalCharges"] = df["TotalCharges"].fillna(0)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   object
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(1), object(18)
memory usage: 1.1+ MB

3) Fix inconsistent categories

Examples:
"No internet service"
"No phone service"
Decide whether to keep them as separate categories or map them

i will replace them with "No" to prevent Data distraction (noise)

In [322]:
def clean_no_service(x:str):
    if x in ["No internet service", "No phone service"]:
        return "No"
    else:
        return x

df["MultipleLines"] = df["MultipleLines"].map(clean_no_service)
df["OnlineSecurity"] = df["OnlineSecurity"].map(clean_no_service)
df["OnlineBackup"] = df["OnlineBackup"].map(clean_no_service)
df["DeviceProtection"] = df["DeviceProtection"].map(clean_no_service)
df["TechSupport"] = df["TechSupport"].map(clean_no_service)
df["StreamingTV"] = df["StreamingTV"].map(clean_no_service)
df["StreamingMovies"] = df["StreamingMovies"].map(clean_no_service)


df[["MultipleLines","OnlineSecurity","OnlineBackup","DeviceProtection","TechSupport","StreamingTV","StreamingMovies"]].head(20)

,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,No,No,Yes,No,No,No,No
1,No,Yes,No,Yes,No,No,No
2,No,Yes,Yes,No,No,No,No
3,No,Yes,No,Yes,Yes,No,No
4,No,No,No,No,No,No,No
5,Yes,No,No,Yes,No,Yes,Yes
6,Yes,No,Yes,No,No,Yes,No
7,No,Yes,No,No,No,No,No
8,Yes,No,No,Yes,Yes,Yes,Yes
9,No,Yes,Yes,No,No,No,No
10,No,Yes,No,No,No,No,No
11,No,No,No,No,No,No,No
12,Yes,No,No,Yes,No,Yes,Yes
13,Yes,No,Yes,Yes,No,Yes,Yes
14,No,Yes,No,Yes,Yes,Yes,Yes
15,Yes,Yes,Yes,Yes,Yes,Yes,Yes
16,No,No,No,No,No,No,No
17,Yes,Yes,No,Yes,No,Yes,Yes
18,No,No,No,Yes,Yes,No,No
19,No,No,Yes,Yes,No,No,Yes

Remove useless columns

customerID should not be a model feature

In [323]:
df.drop("customerID", axis=1)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,No,Yes,No,1,No,No,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,No,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,No,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,No,No,No,45,No,No,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,No,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,No,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No
7039,Female,No,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No
7040,Female,No,Yes,Yes,11,No,No,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,Male,Yes,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes
7042,Male,No,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No

Phase 5 — Feature Engineering (Create New Features)

Goal

Create features that make business sense and improve prediction signal.

1) (New Feature) is_month_to_month              (Logic)  Yes if the contract is monthly, and No otherwise.      (Why it helps)	Those with monthly contracts are the most likely to leave.           (Any risk?)  There is another feature called "tenure" that expresses the same idea, and the two values ​​may conflict.

2) (New Feature)  is_Fiber_optic_subscriber          (Logic)  Yes if the InternetService type is Fiber optic, and No otherwise.   (Why it helps) A very large number of people are leaving the type of internet service(Churn) they subscribe to that is fiber optic.    (Any risk?) It's possible that fiber optic subscribers are using other services simultaneously, which could be the reason for leaving.

3) (New Feature) is_Electronic_check_Payment         (Logic)  Yes if the Payment Method is  Electronic check, and No otherwise.   (Why it helps) Most departing subscribers use Electronic check for payment, which is an inconvenient and time-consuming payment system.


4) (New Feature) is_Active_Digital_User        (Logic)  Yes if the customer is not Senior (SeniorCitizen == 0) and uses electronic billing (PaperlessBilling == Yes)..  (Why it helps) This feature defines the "digital youth" category. This category is the most aware of competing offers, the most frequent users of the internet, and therefore the category that the company needs to make a greater effort to retain because they are "potential leavers" (Churn Candidates) as soon as a cheaper offer comes along (Any risk?):
It may overlap slightly with the original SeniorCitizen feature, but here it has become more precise because it has separated the "digital" youth from the youth who still prefers traditional paper transactions.


5) (New Feature) is_new_customer                   (Logic)  Yes if the user is new user (tenure <= 10), and No otherwise  (Why it helps) The first few months are the "danger phase",if the client gets through it, they will often continue  (Any risk?) The new user might actually be an old user who was absent for a while and has now returned.

 
6) (New Feature) avg_spend_per_month                (Logic)  TotalCharges / (tenure + 1)   (Why it helps). It measures the actual cost  (Any risk?) some outliers will impact in the result

7) (New Feature) youth_loyalty_indicator           (logic)  Yes if the customer is not a Senior  (SeniorCitizen = No) AND has a Two-year contract (Contract == 'Two year').  (Why it helps). It helps to isolate the "more stable" category in the company. If young people commit for long periods, it means that they are mainly dependent on the service (perhaps for work or study) so they will be given the highest priority, while older people may prefer flexible contracts or have difficulty adapting to the company's technical system, which makes their "loyalty" weak. 

8) (New Feature) is_streaming-Fiber-subscriber.  (logic) 1 if it is (Fiber optic + StreamingTV/Movies), and 0 for everything else.  (Why it helps). Fiber optics offers extremely high speeds and stable connections, essential for streaming movies and shows in high definition (4K or HD) without buffering. The goal is to identify the "highest data consumers." These customers are the most valuable to the company, but also the most demanding; any internet speed issue will cause them to switch immediately (Churn Risk).

In [ ]:
TechSupport = df[["Churn","TechSupport"]]
count_TechSupport_Churn = TechSupport.groupby(["Churn","TechSupport"]).size().reset_index(name="count")
count_TechSupport_Churn

  Churn TechSupport  count
0    No          No   3440
1    No         Yes   1734
2   Yes          No   1559
3   Yes         Yes    310

In [226]:
seniorCitizen = df[["Contract","SeniorCitizen"]]
count_seniorCitizen_Churn = seniorCitizen[seniorCitizen["Contract"]== "Two year"]
count_seniorCitizen_Churn.value_counts()

Contract  SeniorCitizen
Two year  No               1550
          Yes               145
Name: count, dtype: int64

In [227]:
gender = df[["Contract","gender"]]
count_gender_Churn = gender[gender["Contract"]== "Two year"]
count_gender_Churn.value_counts()

Contract  gender
Two year  Male      850
          Female    845
Name: count, dtype: int64

In [ ]:
Streaming = df[["StreamingTV","StreamingMovies","InternetService"]]
Streaming_yes = Streaming[(Streaming["StreamingTV"]== "Yes") & (Streaming["StreamingMovies"]== "Yes")]
Streaming_yes.value_counts()

StreamingTV  StreamingMovies  InternetService
Yes          Yes              Fiber optic        1310
                              DSL                 630
Name: count, dtype: int64

In [ ]:
Fiber_Churn = df[["Churn","InternetService"]]
count_Fiber_Churn = Fiber_Churn[(Fiber_Churn["Churn"]== "Yes") & (Fiber_Churn["InternetService"]== "Fiber optic")]
count_Fiber_Churn.value_counts()

Churn  InternetService
Yes    Fiber optic        1297
Name: count, dtype: int64

In [ ]:
#4

dfPaperlessBilling = df[["PaperlessBilling","SeniorCitizen"]]
dfPaperlessBilling = dfPaperlessBilling[(dfPaperlessBilling["PaperlessBilling"] == "Yes")]
dfPaperlessBilling.value_counts()

PaperlessBilling  SeniorCitizen
Yes               No               3295
                  Yes               876
Name: count, dtype: int64

In [ ]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [ ]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [ ]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [ ]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [ ]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [ ]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [ ]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [ ]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [ ]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [ ]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [ ]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

Now I will  create the new Features

1) (New Feature) is_month_to_month

In [282]:
df["is_month_to_month"] = df["Contract"].apply(lambda x: "Yes" if x == "Month-to-month" else "No")

2) (New Feature)  is_Fiber_optic_subscriber

In [285]:
df["is_Fiber_optic_subscriber"] = df["InternetService"].apply(lambda x: "Yes" if x == "Fiber optic" else "No")

3) (New Feature) is_Electronic_check_Payment

In [288]:
df["is_Electronic_check_Payment"] = df["PaymentMethod"].apply(lambda x: "Yes" if x == "Electronic check" else "No")

4) (New Feature) is_Active_Digital_User

In [347]:
df["is_Active_Digital_User"] = df.apply(
    lambda row: "Yes" if row["PaperlessBilling"] == "Yes" and row["SeniorCitizen"] == "No" else "No", 
    axis=1
)

5) (New Feature) is_new_customer

In [332]:
df["is_new_customer"] = df["tenure"].apply(lambda x: "Yes" if x <= 10 else "No")

6) (New Feature) avg_spend_per_month

In [ ]:
# use this logic TotalCharges / (tenure + 1) in apply
df["avg_spend_per_month"] = df.apply(lambda row: row["TotalCharges"] / (row["tenure"] + 1), axis=1)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,is_Active_Digital_User,is_new_customer,avg_spend_per_month
0,7590-VHVEG,Female,No,Yes,No,1,No,No,DSL,No,...,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,Yes,Yes,14.925000
1,5575-GNVDE,Male,No,No,No,34,Yes,No,DSL,Yes,...,No,One year,No,Mailed check,56.95,1889.50,No,No,No,53.985714
2,3668-QPYBK,Male,No,No,No,2,Yes,No,DSL,Yes,...,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,Yes,Yes,36.050000
3,7795-CFOCW,Male,No,No,No,45,No,No,DSL,Yes,...,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,No,No,40.016304
4,9237-HQITU,Female,No,No,No,2,Yes,No,Fiber optic,No,...,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,Yes,Yes,50.550000

7) (New Feature) youth_loyalty_indicator

In [342]:
# Yes if user is not senior (High Loyalty Potential) , and No otherwise
df["youth_loyalty_indicator"] = df["SeniorCitizen"].apply(lambda x: "No" if x == "Yes" else "Yes")

8) (New Feature) is_streaming-Fiber-subscriber.

In [346]:
# use yes if it is (Fiber optic + StreamingTV/Movies), and No for everything else
df["is_streaming-Fiber-subscriber"] = df.apply(lambda row: "Yes" if (row["InternetService"] == "Fiber optic" and (row["StreamingTV"] == "Yes" or row["StreamingMovies"] == "Yes")) else "No", axis=1)

Phase 7 — Explore Relationships (Based on Your Features)




Hypothesis 1: Streaming as a Driver for Fiber Adoption

The hypothesis: Customers interested in streaming services (Streaming TV & Movies) are the primary category that require fiber optic service to ensure strong and stable internet speeds.

Supporting Data:
Based on the "is_streaming-Fiber-subscriber" feature that links the three together, we observe that most streaming service subscribers are concentrated in the Fiber Optic category rather than DSL.

Streaming = df[["StreamingTV","StreamingMovies","InternetService"]]
Streaming_yes = Streaming[(Streaming["StreamingTV"]== "Yes") & (Streaming["StreamingMovies"]== "Yes")]
Streaming_yes.value_counts()

Explanation: The primary motivation behind a customer subscribing to fiber optic service is not simply having fast internet, but rather the "technical necessity" to run high-quality (4K/HD) streaming platforms without buffering. This means that streaming is the "magnet" that attracts customers to the company's most expensive internet packages.

Business Insight: Since streaming is the primary driver of demand for strong internet, the company should create marketing offers that combine streaming platform subscriptions (such as Netflix or Shahid) with fiber optic packages. This integration will make the customer feel that the company understands their true need, reducing the likelihood of them churning out as long as their viewing experience is excellent.




Hypothesis 2: The Fiber Optic Churn Crisis

The hypothesis: Although fiber optic service offers the best quality internet, it has the highest churn rates compared to DSL services or customers without internet.

Supporting Data: * When analyzing the "InternetService" , we find that a very large percentage of departing customers (Churn = Yes) belong to this specific category("Fiber Optic).

Fiber_Churn = df[["Churn","InternetService"]]
count_Fiber_Churn = Fiber_Churn[(Fiber_Churn["Churn"]== "Yes") & (Fiber_Churn["InternetService"]== "Fiber optic")]
count_Fiber_Churn.value_counts()

Explanation:
There's a strange contradiction here; Viber is faster, yet it drives customers away! The logical explanation is that these customers are paying high prices for the service, and if the "value for money" isn't clear to them, or if they encounter even a minor technical issue, they leave immediately because the high bill makes them unwilling to tolerate any mistakes. Furthermore, the company's competitors often target Viber users with very attractive "switch" offers.

Business Insight:
The company should immediately conduct an exit survey with these customers to determine whether the reason for leaving was price or underlying technical issues. Price lock packages should also be offered to fiber customers to ensure they don't switch to competitors to save a few dollars.


Hypothesis 3: The "Youth Anchor" Stability

The hypothesis: Young people are the group that most demonstrates loyalty to the company, as they represent the largest percentage of subscribers committed to long-term contracts (two years) to ensure the stability of their digital services.

Supporting Data:

By analyzing the relationship between contract type and age group using this code:

seniorCitizen = df[["Contract","SeniorCitizen"]]
count_seniorCitizen_Churn = seniorCitizen[seniorCitizen["Contract"]== "Two year"]
count_seniorCitizen_Churn.value_counts()

we found that the vast majority of two-year contract holders are young (SeniorCitizen = No), while older individuals represent a minority in this type of long-term contract.

This numerically demonstrates that "long-term commitment" is a behavior associated with younger individuals at this company.

Explanation: Contrary to the common belief that young people are always looking for change, data shows that when they find a service that meets their needs (study, work, entertainment), they become the most committed to it and opt for two-year contracts to ensure price and service stability. This long-term commitment makes them the most loyal customers and the most deserving of the company's attention.

Business Insight:
Since these young people are the ones who commit to the company for the longest possible period, they should be given "Highest Priority." Investing in this group is a sure thing, because their early loyalty and commitment to long-term contracts mean sustained profits for the company for years to come.


Hypothesis 4: Youth as the Leaders of Digital Adoption

The hypothesis: Young people (not the elderly) are the most dependent and frequent users of the electronic billing service (Paperless Billing), making them the company's primary digital interface.

Supporting Data:
Based on the is_Active_Digital_User feature you designed, the data shows that the younger demographic (SeniorCitizen = No) is four times more likely to use e-billing than older adults.
The data confirms that these "digital youth" are the most frequent users of internet services in general, linking their age group to their technological lifestyle.

using this code :
dfPaperlessBilling = df[["PaperlessBilling","SeniorCitizen"]]
dfPaperlessBilling = dfPaperlessBilling[(dfPaperlessBilling["PaperlessBilling"] == "Yes")]
dfPaperlessBilling.value_counts()

Explanation:
This generation prefers speed and efficiency; they don't wait for paper mail but prefer to manage their finances with the click of a button. This feature (is_Active_Digital_User) enabled us to isolate "digital youth" from "traditional youth," revealing that the digital generation is the most aware of everything new in the market and the most frequent consumers of internet services, making them the "thermometer" that measures the development of the company's services.

Business Insight:
Since young people are the most reliant on digital channels, companies should focus their customer retention efforts on digital notifications (app notifications) and quick online offers. These customers are "potentially leaving" only if they feel the company isn't evolving technologically at their pace, so retaining them requires continuous innovation in the digital user experience.