In [268]:
import pandas as pd
df = pd.read_csv('Telco.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [269]:
df["Churn"].value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

1) EDA Summary (insights + target understanding)

A short summary (5–8 lines):
What the dataset is about
What the target is
3 issues you already suspect
  

  The data pertains to the customers of a telecommunications company and includes demographic details, shared services (internet, telephone), and financial contract details,target is the Churn column (Did the customer leave the company or not?).
  issues I suspect :
  1- Because the data type in TotalCharges is Object, there are values ​​that are empty spaces that are counted as non-Nan when they are actually empty.
  2- There are values ​​labeled "No internet service" in the service columns; these cause problems in analysis. It's best to simply count them as "No" and be done with it.
  3- SeniorCitizen column must be object not number

In [270]:
seniorCitizen = df[["SeniorCitizen"]]
seniorCitizen.describe()
seniorCitizen.value_counts()

SeniorCitizen
0                5901
1                1142
Name: count, dtype: int64

In [271]:
df["TotalCharges"].describe()

count     7043
unique    6531
top
freq        11
Name: TotalCharges, dtype: object

2) Cleaning Log (table)
column          current type      correct type
SeniorCitizen	Int64 (0/1)	    Category/Boolean	      (yes,no)تمثل صفة وليست رقماً حسابياً
TotalCharges	Object	         Float64	            يمثل مبالغ مالية ويجب إجراء عمليات حسابية عليه

In [272]:
df["TotalCharges"].describe()
subset = df[["tenure", "TotalCharges"]]
df_zero_tenure = subset[(df["tenure"] == 0)]
df_zero_tenure

      tenure TotalCharges
488        0
753        0
936        0
1082       0
1340       0
3331       0
3826       0
4380       0
5218       0
6670       0
6754       0

In [273]:
df["customerID"].duplicated().any()

False

Phase 3 — Data Quality Check (Before Cleaning)
Tasks
Investigate:
Missing values (count + percentage)
- Duplicates (customerID duplicates?)
 No 
 df["customerID"].duplicated().any()
 return false
 
- Invalid values (examples: empty strings, spaces, weird categories)
Outliers (MonthlyCharges, TotalCharges)


Deliverable
Write findings in this format:
Problem → Evidence → Impact

Problem 1:
There are empty spaces in some values ​​in the "TotalCharges" column.
Evidence:
When performing a group by for the TotalCharges of subscribers whose  "tenure equal zero, empty values ​​appear.
Impact:
Calculations fail (such as the average when I try to describe it).

Problem 2:
The "TotalCharges" column is defined as an Object (Text) instead of a Float.
Evidence:
the column contains decimal numbers, but the system reads them as text 
Impact → Inability to perform statistical analysis or calculate 

Problem 3:
Redundant categories such as "No internet service" and "No phone service".
Evidence → In columns such as OnlineSecurity or MultipleLines.
Impact → Data distraction (noise) leading to incorrect analysis.


Problem 4:
The "SeniorCitizen" column is stored as an int64 (0 and 1)
Evidence → It appears in the data as numbers, which may cause analysis programs to treat it as a numerical quantity.
Impact → It misleads descriptive analysis

Phase 4 — Data Cleaning (Execute + Explain)

Goal

Fix the dataset so it becomes consistent and usable.

Tasks (must be done)

Fix data types

Convert TotalCharges into numeric
Convert SeniorCitizen from binary (0/1) to object Category

In [274]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [275]:
df["SeniorCitizen"] = df["SeniorCitizen"].replace({1: "Yes", 0: "No"})
df.info()
df["SeniorCitizen"].value_counts()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   object
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(1), object(18)
memory usage: 1.1+ MB

SeniorCitizen
No     5901
Yes    1142
Name: count, dtype: int64

2) Handle missing values

Identify why values are missing (example: TotalCharges missing when tenure is 0)
  Because he is a new user and has not yet made any payments.
Choose a strategy:
drop rows (only if very small)
fill with median/0 (only if justified)

   i will fill with zero   Because he is a new user and has not yet made any payments.

In [276]:
df["TotalCharges"] = df["TotalCharges"].fillna(0)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   object
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(1), object(18)
memory usage: 1.1+ MB

3) Fix inconsistent categories

Examples:
"No internet service"
"No phone service"
Decide whether to keep them as separate categories or map them

i will replace them with "No" to prevent Data distraction (noise)

In [277]:
def clean_no_service(x:str):
    if x in ["No internet service", "No phone service"]:
        return "No"
    else:
        return x

df["MultipleLines"] = df["MultipleLines"].map(clean_no_service)
df["OnlineSecurity"] = df["OnlineSecurity"].map(clean_no_service)
df["OnlineBackup"] = df["OnlineBackup"].map(clean_no_service)
df["DeviceProtection"] = df["DeviceProtection"].map(clean_no_service)
df["TechSupport"] = df["TechSupport"].map(clean_no_service)
df["StreamingTV"] = df["StreamingTV"].map(clean_no_service)
df["StreamingMovies"] = df["StreamingMovies"].map(clean_no_service)


df[["MultipleLines","OnlineSecurity","OnlineBackup","DeviceProtection","TechSupport","StreamingTV","StreamingMovies"]].head(20)

,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,No,No,Yes,No,No,No,No
1,No,Yes,No,Yes,No,No,No
2,No,Yes,Yes,No,No,No,No
3,No,Yes,No,Yes,Yes,No,No
4,No,No,No,No,No,No,No
5,Yes,No,No,Yes,No,Yes,Yes
6,Yes,No,Yes,No,No,Yes,No
7,No,Yes,No,No,No,No,No
8,Yes,No,No,Yes,Yes,Yes,Yes
9,No,Yes,Yes,No,No,No,No
10,No,Yes,No,No,No,No,No
11,No,No,No,No,No,No,No
12,Yes,No,No,Yes,No,Yes,Yes
13,Yes,No,Yes,Yes,No,Yes,Yes
14,No,Yes,No,Yes,Yes,Yes,Yes
15,Yes,Yes,Yes,Yes,Yes,Yes,Yes
16,No,No,No,No,No,No,No
17,Yes,Yes,No,Yes,No,Yes,Yes
18,No,No,No,Yes,Yes,No,No
19,No,No,Yes,Yes,No,No,Yes

Remove useless columns

customerID should not be a model feature

In [278]:
df.drop("customerID", axis=1)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,No,Yes,No,1,No,No,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,No,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,No,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,No,No,No,45,No,No,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,No,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,No,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No
7039,Female,No,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No
7040,Female,No,Yes,Yes,11,No,No,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,Male,Yes,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes
7042,Male,No,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No

Phase 5 — Feature Engineering (Create New Features)

Goal

Create features that make business sense and improve prediction signal.

1) (New Feature) is_month_to_month              (Logic)  Yes if the contract is monthly, and No otherwise.      (Why it helps)	Those with monthly contracts are the most likely to leave.           (Any risk?)  There is another feature called "tenure" that expresses the same idea, and the two values ​​may conflict.

2) (New Feature)  is_Fiber_optic_subscriber          (Logic)  Yes if the InternetService type is Fiber optic, and No otherwise.   (Why it helps) A very large number of people are leaving the type of internet service(Churn) they subscribe to that is fiber optic.    (Any risk?) It's possible that fiber optic subscribers are using other services simultaneously, which could be the reason for leaving.

3) (New Feature) is_Electronic_check_Payment         (Logic)  Yes if the Payment Method is  Electronic check, and No otherwise.   (Why it helps) Most departing subscribers use Electronic check for payment, which is an inconvenient and time-consuming payment system.


4) (New Feature) is_Active_Digital_User        (Logic)  Yes if the customer is not Senior (SeniorCitizen == 0) and uses electronic billing (PaperlessBilling == Yes)..  (Why it helps) This feature defines the "digital youth" category. This category is the most aware of competing offers, the most frequent users of the internet, and therefore the category that the company needs to make a greater effort to retain because they are "potential leavers" (Churn Candidates) as soon as a cheaper offer comes along (Any risk?):
It may overlap slightly with the original SeniorCitizen feature, but here it has become more precise because it has separated the "digital" youth from the youth who still prefers traditional paper transactions.


5) (New Feature) is_new_customer                   (Logic)  Yes if the user is new user (tenure <= 10), and No otherwise  (Why it helps) The first few months are the "danger phase",if the client gets through it, they will often continue  (Any risk?) The new user might actually be an old user who was absent for a while and has now returned.

 
6) (New Feature) avg_spend_per_month                (Logic)  TotalCharges / (tenure + 1)   (Why it helps). It measures the actual cost  (Any risk?) some outliers will impact in the result

7) (New Feature) youth_loyalty_indicator           (logic)  Yes if the customer is not a Senior  (SeniorCitizen = No) AND has a Two-year contract (Contract == 'Two year').  (Why it helps). It helps to isolate the "more stable" category in the company. If young people commit for long periods, it means that they are mainly dependent on the service (perhaps for work or study) so they will be given the highest priority, while older people may prefer flexible contracts or have difficulty adapting to the company's technical system, which makes their "loyalty" weak. 

8) (New Feature) is_streaming-Fiber-subscriber.  (logic) 1 if it is (Fiber optic + StreamingTV/Movies), and 0 for everything else.  (Why it helps). Fiber optics offers extremely high speeds and stable connections, essential for streaming movies and shows in high definition (4K or HD) without buffering. The goal is to identify the "highest data consumers." These customers are the most valuable to the company, but also the most demanding; any internet speed issue will cause them to switch immediately (Churn Risk).

In [279]:
TechSupport = df[["Churn","TechSupport"]]
count_TechSupport_Churn = TechSupport.groupby(["Churn","TechSupport"]).size().reset_index(name="count")
count_TechSupport_Churn

  Churn TechSupport  count
0    No          No   3440
1    No         Yes   1734
2   Yes          No   1559
3   Yes         Yes    310

In [198]:
seniorCitizen = df[["Contract","SeniorCitizen"]]
count_seniorCitizen_Churn = seniorCitizen[seniorCitizen["Contract"]== "Two year"]
count_seniorCitizen_Churn.value_counts()

Contract  SeniorCitizen
Two year  0                1550
          1                 145
Name: count, dtype: int64

In [199]:
gender = df[["Contract","gender"]]
count_gender_Churn = gender[gender["Contract"]== "Two year"]
count_gender_Churn.value_counts()

Contract  gender
Two year  Male      850
          Female    845
Name: count, dtype: int64

In [200]:
Streaming = df[["StreamingTV","StreamingMovies","InternetService"]]
Streaming_yes = Streaming[(Streaming["StreamingTV"]== "Yes") & (Streaming["StreamingMovies"]== "Yes")]
Streaming_yes.value_counts()

StreamingTV  StreamingMovies  InternetService
Yes          Yes              Fiber optic        1310
                              DSL                 630
Name: count, dtype: int64

In [ ]:
Fiber_Churn = df[["Churn","InternetService"]]
count_Fiber_Churn = Fiber_Churn[(Fiber_Churn["Churn"]== "Yes") & (Fiber_Churn["InternetService"]== "Fiber optic")]
count_Fiber_Churn.value_counts()

Churn  InternetService
Yes    Fiber optic        1297
Name: count, dtype: int64

In [201]:
#4

dfPaperlessBilling = df[["PaperlessBilling","SeniorCitizen"]]
dfPaperlessBilling = dfPaperlessBilling[(dfPaperlessBilling["PaperlessBilling"] == "Yes")]
dfPaperlessBilling.value_counts()

PaperlessBilling  SeniorCitizen
Yes               0                3295
                  1                 876
Name: count, dtype: int64

In [280]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   object
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(1), object(18)
memory usage: 1.1+ MB

Now I will  create the new Features

1) (New Feature) is_month_to_month

In [281]:
df["is_month_to_month"] = df["Contract"].apply(lambda x: "Yes" if x == "Month-to-month" else "No")

2) (New Feature)  is_Fiber_optic_subscriber

In [282]:
df["is_Fiber_optic_subscriber"] = df["InternetService"].apply(lambda x: "Yes" if x == "Fiber optic" else "No")

3) (New Feature) is_Electronic_check_Payment

In [283]:
df["is_Electronic_check_Payment"] = df["PaymentMethod"].apply(lambda x: "Yes" if x == "Electronic check" else "No")

4) (New Feature) is_Active_Digital_User

In [284]:
df["is_Active_Digital_User"] = df.apply(
    lambda row: "Yes" if row["PaperlessBilling"] == "Yes" and row["SeniorCitizen"] == "No" else "No", 
    axis=1
)

5) (New Feature) is_new_customer

In [285]:
df["is_new_customer"] = df["tenure"].apply(lambda x: "Yes" if x <= 10 else "No")

6) (New Feature) avg_spend_per_month

In [286]:
# use this logic TotalCharges / (tenure + 1) in apply
df["avg_spend_per_month"] = df.apply(lambda row: row["TotalCharges"] / (row["tenure"] + 1), axis=1)

7) (New Feature) youth_loyalty_indicator

In [287]:
# Yes if user is not senior (High Loyalty Potential) , and No otherwise
df["youth_loyalty_indicator"] = df["SeniorCitizen"].apply(lambda x: "No" if x == "Yes" else "Yes")

8) (New Feature) is_streaming-Fiber-subscriber.

In [288]:
# use yes if it is (Fiber optic + StreamingTV/Movies), and No for everything else
df["is_streaming-Fiber-subscriber"] = df.apply(lambda row: "Yes" if (row["InternetService"] == "Fiber optic" and (row["StreamingTV"] == "Yes" or row["StreamingMovies"] == "Yes")) else "No", axis=1)

Phase 7 — Explore Relationships (Based on Your Features)




Hypothesis 1: Streaming as a Driver for Fiber Adoption

The hypothesis: Customers interested in streaming services (Streaming TV & Movies) are the primary category that require fiber optic service to ensure strong and stable internet speeds.

Supporting Data:
Most streaming subscribers are concentrated in the Fiber Optic category rather than DSL..

Streaming = df[["StreamingTV","StreamingMovies","InternetService"]]
Streaming_yes = Streaming[(Streaming["StreamingTV"]== "Yes") & (Streaming["StreamingMovies"]== "Yes")]
Streaming_yes.value_counts()

Explanation: The primary motivation behind a customer subscribing to fiber optic service is not simply having fast internet, but rather the "technical necessity" to run high-quality (4K/HD) streaming platforms without buffering. This means that streaming is the "magnet" that attracts customers to the company's most expensive internet packages.

Business Insight: Since streaming is the primary driver of demand for strong internet, the company should create marketing offers that combine streaming platform subscriptions (such as Netflix or Shahid) with fiber optic packages.




Hypothesis 2: The Fiber Optic Churn Crisis

The hypothesis: Although fiber optic service offers the best quality internet, it has the highest churn rates compared to DSL services or customers without internet.

Supporting Data: When analyzing the "InternetService" , we find that a very large percentage of departing customers (Churn = Yes) belong to this specific category("Fiber Optic).

Fiber_Churn = df[["Churn","InternetService"]]
count_Fiber_Churn = Fiber_Churn[(Fiber_Churn["Churn"]== "Yes") & (Fiber_Churn["InternetService"]== "Fiber optic")]
count_Fiber_Churn.value_counts()

Explanation:
The high bill makes the customer less tolerant of any technical error, and they are also heavily targeted by competitors' offers.

Business Insight:
It is necessary to conduct exit surveys and offer price lock packages to retain them.





Hypothesis 3: The "Youth Anchor" Stability

The hypothesis: Young people are the group that most demonstrates loyalty to the company, as they represent the largest percentage of subscribers committed to long-term contracts (two years)

Supporting Data:

By analyzing the relationship between contract type and age group using this code:

seniorCitizen = df[["Contract","SeniorCitizen"]]
count_seniorCitizen_Churn = seniorCitizen[seniorCitizen["Contract"]== "Two year"]
count_seniorCitizen_Churn.value_counts()

we found that the vast majority of two-year contract holders are young (SeniorCitizen = No), while older individuals represent a minority in this type of long-term contract.

This numerically demonstrates that "long-term commitment" is a behavior associated with younger individuals at this company.

Explanation: When young people find a service that meets their digital needs, they prefer stability to ensure price and quality, making them "the most sustainable customers".

Business Insight:
This category is given "top priority" in support and rewards to ensure their survival as a long-term investment.






Hypothesis 4: Youth as the Leaders of Digital Adoption

The hypothesis: Young people (not the elderly) are the most dependent and frequent users of the electronic billing service (Paperless Billing), making them the company's primary digital interface.

Supporting Data: Young people are up to 4 times more likely to use electronic billing than older people.

using this code :
dfPaperlessBilling = df[["PaperlessBilling","SeniorCitizen"]]
dfPaperlessBilling = dfPaperlessBilling[(dfPaperlessBilling["PaperlessBilling"] == "Yes")]
dfPaperlessBilling.value_counts()

Explanation:
This generation prefers speed and efficiency; they don't wait for paper mail but prefer to manage their finances with the click of a button. This feature (is_Active_Digital_User) enabled us to isolate "digital youth" from "traditional youth," revealing that the digital generation is the most aware of everything new in the market and the most frequent consumers of internet services, making them the "thermometer" that measures the development of the company's services.

Business Insight:
Since young people are the most reliant on digital channels, companies should focus their customer retention efforts on digital notifications (app notifications) and quick online offers. These customers are "potentially leaving" only if they feel the company isn't evolving technologically at their pace, so retaining them requires continuous innovation in the digital user experience.

In [289]:
# drop two Columns (StreamingTV , StreamingMovies) and make a new columns called Streaming from (StreamingTV (Yes NO) Or StreamingMovies (Yes NO))
df['Streaming'] = df['StreamingTV'].replace({'Yes': 1, 'No': 0}) | df['StreamingMovies'].replace({'Yes': 1, 'No': 0})
df = df.drop(['StreamingTV', 'StreamingMovies'], axis=1)

/var/folders/vh/r6nxrl6d77l55d90cffv85rw0000gn/T/ipykernel_13351/4060655549.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Streaming'] = df['StreamingTV'].replace({'Yes': 1, 'No': 0}) | df['StreamingMovies'].replace({'Yes': 1, 'No': 0})

In [ ]:
!pip install matplotlib seaborn pandas numpy scipy

In [ ]:
!pip install datasist

1) Detect and Handle Outliers

In [37]:
from datasist.structdata import detect_outliers

In [290]:
numeric_features = df.select_dtypes(include=['number']).columns
numeric_features =["tenure", "MonthlyCharges", "TotalCharges","avg_spend_per_month"]
outliers_indices = detect_outliers(df, 0, numeric_features)
len(outliers_indices)

0

2) Deal with Imbalanced classes

In [216]:
df["Churn"].value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [ ]:
!pip install imbalanced-learn

In [312]:
from imblearn.over_sampling import RandomOverSampler

X = df.drop('Churn', axis=1)
y = df['Churn']

ros = RandomOverSampler(random_state=42)

X_resampled, y_resampled = ros.fit_resample(X, y)

y_resampled

0        0
1        0
2        1
3        0
4        1
        ..
10343    1
10344    1
10345    1
10346    1
10347    1
Name: Churn, Length: 10348, dtype: int64

In [313]:
df = pd.DataFrame(X_resampled, columns=X.columns)
df['Churn'] = y_resampled
X_resampled

,customerID,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,...,PaymentMethod_Electronic check,PaymentMethod_Mailed check,Contract_Month-to-month,Contract_One year,Contract_Two year,gender_Female,gender_Male,InternetService_DSL,InternetService_Fiber optic,InternetService_No
0,7590-VHVEG,0,1,0,1,0,0,0,1,0,...,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
1,5575-GNVDE,0,0,0,34,1,0,1,0,1,...,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0
2,3668-QPYBK,0,0,0,2,1,0,1,1,0,...,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
3,7795-CFOCW,0,0,0,45,0,0,1,0,1,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0
4,9237-HQITU,0,0,0,2,1,0,0,0,0,...,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10343,7623-TRNQN,0,0,1,1,1,0,0,0,0,...,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
10344,8580-AECUZ,1,0,0,1,1,0,0,0,0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
10345,0661-XEYAN,1,0,0,1,0,0,0,0,0,...,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
10346,0362-ZBZWJ,0,0,0,36,1,1,0,0,0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
10347,5515-IDEJJ,0,1,1,1,1,0,0,0,0,...,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0

3) Work with Categorical data

In [314]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

num_cols = ['SeniorCitizen']

df['SeniorCitizen'] = le.fit_transform(df['SeniorCitizen'])
print(df[['SeniorCitizen']].head(30))

    SeniorCitizen
0               0
1               0
2               0
3               0
4               0
5               0
6               0
7               0
8               0
9               0
10              0
11              0
12              0
13              0
14              0
15              0
16              0
17              0
18              0
19              0
20              1
21              0
22              0
23              0
24              0
25              0
26              0
27              0
28              0
29              0

In [315]:
# make the same for phone
df['PhoneService'] = le.fit_transform(df['PhoneService'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10348 entries, 0 to 10347
Data columns (total 36 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   customerID                               10348 non-null  object
 1   SeniorCitizen                            10348 non-null  int64
 2   Partner                                  10348 non-null  int64
 3   Dependents                               10348 non-null  int64
 4   tenure                                   10348 non-null  int64
 5   PhoneService                             10348 non-null  int64
 6   MultipleLines                            10348 non-null  int64
 7   OnlineSecurity                           10348 non-null  int64
 8   OnlineBackup                             10348 non-null  int64
 9   DeviceProtection                         10348 non-null  int64
 10  TechSupport                              10348 non-null  int64
 11  PaperlessBilling                         10348 non-null  int64
 12  MonthlyCharges                           10348 non-null  float64
 13  TotalCharges                             10348 non-null  float64
 14  is_month_to_month                        10348 non-null  int64
 15  is_Fiber_optic_subscriber                10348 non-null  int64
 16  is_Electronic_check_Payment              10348 non-null  int64
 17  is_Active_Digital_User                   10348 non-null  int64
 18  is_new_customer                          10348 non-null  int64
 19  avg_spend_per_month                      10348 non-null  float64
 20  youth_loyalty_indicator                  10348 non-null  int64
 21  is_streaming-Fiber-subscriber            10348 non-null  int64
 22  Streaming                                10348 non-null  int64
 23  PaymentMethod_Bank transfer (automatic)  10348 non-null  float64
 24  PaymentMethod_Credit card (automatic)    10348 non-null  float64
 25  PaymentMethod_Electronic check           10348 non-null  float64
 26  PaymentMethod_Mailed check               10348 non-null  float64
 27  Contract_Month-to-month                  10348 non-null  float64
 28  Contract_One year                        10348 non-null  float64
 29  Contract_Two year                        10348 non-null  float64
 30  gender_Female                            10348 non-null  float64
 31  gender_Male                              10348 non-null  float64
 32  InternetService_DSL                      10348 non-null  float64
 33  InternetService_Fiber optic              10348 non-null  float64
 34  InternetService_No                       10348 non-null  float64
 35  Churn                                    10348 non-null  int64
dtypes: float64(15), int64(20), object(1)
memory usage: 2.8+ MB

In [317]:
#make the same for all cols have zeros one such as MultipleLines , OnlineSecurity , OnlineBackup ,DeviceProtection , TechSupport , Streaming
#make the same for all cols have zeros one such as MultipleLines , OnlineSecurity , OnlineBackup ,DeviceProtection , TechSupport , Streaming Partner           7043 non-null   object
cols_to_encode = ['MultipleLines', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'Streaming', 'is_month_to_month', 'is_Fiber_optic_subscriber', 'is_Electronic_check_Payment', 'is_Active_Digital_User', 'is_new_customer', 'youth_loyalty_indicator', 'is_streaming-Fiber-subscriber', 'Streaming','Churn','PaperlessBilling',"Dependents","Partner"]
for col in cols_to_encode:
    df[col] = le.fit_transform(df[col])

df

,customerID,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,...,PaymentMethod_Mailed check,Contract_Month-to-month,Contract_One year,Contract_Two year,gender_Female,gender_Male,InternetService_DSL,InternetService_Fiber optic,InternetService_No,Churn
0,7590-VHVEG,0,1,0,1,0,0,0,1,0,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0
1,5575-GNVDE,0,0,0,34,1,0,1,0,1,...,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0
2,3668-QPYBK,0,0,0,2,1,0,1,1,0,...,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1
3,7795-CFOCW,0,0,0,45,0,0,1,0,1,...,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0
4,9237-HQITU,0,0,0,2,1,0,0,0,0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10343,7623-TRNQN,0,0,1,1,1,0,0,0,0,...,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1
10344,8580-AECUZ,1,0,0,1,1,0,0,0,0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1
10345,0661-XEYAN,1,0,0,1,0,0,0,0,0,...,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1
10346,0362-ZBZWJ,0,0,0,36,1,1,0,0,0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1
10347,5515-IDEJJ,0,1,1,1,1,0,0,0,0,...,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1

In [ ]:
from sklearn.preprocessing import OneHotEncoder
Encoder = OneHotEncoder(sparse_output=False)
Transformed_InternetService = Encoder.fit_transform(df[['InternetService']])
Transformed_InternetService = pd.DataFrame(Transformed_InternetService , columns= Encoder.get_feature_names_out())
df.drop(columns=['InternetService'], inplace=True)
df = pd.concat([df, Transformed_InternetService], axis=1)

In [ ]:
# make the same transformation for 'PaymentMethod'
Encoder = OneHotEncoder(sparse_output=False)
Transformed_PaymentMethod = Encoder.fit_transform(df[['PaymentMethod']])
Transformed_PaymentMethod = pd.DataFrame(Transformed_PaymentMethod , columns= Encoder.get_feature_names_out())
df = pd.concat([df,Transformed_PaymentMethod] , axis = 1 )
if 'PaymentMethod' in df.columns:
    df.drop('PaymentMethod' , axis = 1 , inplace =True)
df

In [ ]:
# make the same transformation for 'Contract'
Encoder = OneHotEncoder(sparse_output=False)
Transformed_Contract = Encoder.fit_transform(df[['Contract']])
Transformed_Contract = pd.DataFrame(Transformed_Contract , columns= Encoder.get_feature_names_out())
df = pd.concat([df,Transformed_Contract] , axis = 1 )
if 'Contract' in df.columns:
    df.drop('Contract' , axis = 1 , inplace =True)
df

In [ ]:
# make the same transformation for 'gender'
Encoder = OneHotEncoder(sparse_output=False)
Transformed_Gender = Encoder.fit_transform(df[['gender']])
Transformed_Gender = pd.DataFrame(Transformed_Gender , columns= Encoder.get_feature_names_out())
df = pd.concat([df,Transformed_Gender] , axis = 1 )
if 'gender' in df.columns:
    df.drop('gender' , axis = 1 , inplace =True)
df

In [321]:
df

,customerID,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,...,PaymentMethod_Mailed check,Contract_Month-to-month,Contract_One year,Contract_Two year,gender_Female,gender_Male,InternetService_DSL,InternetService_Fiber optic,InternetService_No,Churn
0,7590-VHVEG,0,1,0,1,0,0,0,1,0,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0
1,5575-GNVDE,0,0,0,34,1,0,1,0,1,...,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0
2,3668-QPYBK,0,0,0,2,1,0,1,1,0,...,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1
3,7795-CFOCW,0,0,0,45,0,0,1,0,1,...,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0
4,9237-HQITU,0,0,0,2,1,0,0,0,0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10343,7623-TRNQN,0,0,1,1,1,0,0,0,0,...,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1
10344,8580-AECUZ,1,0,0,1,1,0,0,0,0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1
10345,0661-XEYAN,1,0,0,1,0,0,0,0,0,...,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1
10346,0362-ZBZWJ,0,0,0,36,1,1,0,0,0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1
10347,5515-IDEJJ,0,1,1,1,1,0,0,0,0,...,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1

4) Split data to Train and Test Sets

In [322]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=42)
X_train
y_test

9428    1
4593    0
5379    0
8918    1
6448    1
       ..
6425    0
766     0
1144    1
3065    0
7073    1
Name: Churn, Length: 2070, dtype: int64

5) Feature Scaling
فقط للاعمدة ذات القيم العددية المستمره (مش 1,0)

In [323]:
df["tenure"].describe()
# بما ان مافي اوتلاير كبيره وكمان الانحراف المعياري  صغير والقيم متوزعه على نطاق واسع اذا سوف نستخدم StandardScaler

count    10348.000000
mean        27.649401
std         24.051273
min          0.000000
25%          5.000000
50%         21.000000
75%         49.000000
max         72.000000
Name: tenure, dtype: float64

In [324]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df["tenure"] = scaler.fit_transform(df[["tenure"]])
df["tenure"].describe()

count    1.034800e+04
mean     1.098636e-17
std      1.000048e+00
min     -1.149658e+00
25%     -9.417587e-01
50%     -2.764811e-01
75%      8.877547e-01
max      1.844091e+00
Name: tenure, dtype: float64

In [325]:
df["MonthlyCharges"].describe()

count    10348.000000
mean        67.792685
std         28.723644
min         18.250000
25%         45.400000
50%         74.500000
75%         90.600000
max        118.750000
Name: MonthlyCharges, dtype: float64

In [326]:
scaler = StandardScaler()
df["MonthlyCharges"] = scaler.fit_transform(df[["MonthlyCharges"]])
df["MonthlyCharges"].describe()

count    1.034800e+04
mean    -3.240976e-16
std      1.000048e+00
min     -1.724888e+00
25%     -7.796283e-01
50%      2.335233e-01
75%      7.940642e-01
max      1.774140e+00
Name: MonthlyCharges, dtype: float64

In [266]:
df["TotalCharges"].describe()
#البيانات فيها outliers كثيرة وواضحة.
#الحل الأفضل هنا هو استخدام RobustScaler

count    10348.000000
mean      2029.178242
std       2183.141383
min          0.000000
25%        273.000000
50%       1135.700000
75%       3233.600000
max       8684.800000
Name: TotalCharges, dtype: float64

In [327]:
from sklearn.preprocessing import RobustScaler
scaler = RobustScaler()
df["TotalCharges"] = scaler.fit_transform(df[["TotalCharges"]])
df["TotalCharges"].describe()

count    10348.000000
mean         0.301790
std          0.737398
min         -0.383605
25%         -0.291394
50%          0.000000
75%          0.708606
max          2.549855
Name: TotalCharges, dtype: float64

In [328]:
df

,customerID,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,...,PaymentMethod_Mailed check,Contract_Month-to-month,Contract_One year,Contract_Two year,gender_Female,gender_Male,InternetService_DSL,InternetService_Fiber optic,InternetService_No,Churn
0,7590-VHVEG,0,1,0,-1.108078,0,0,0,1,0,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0
1,5575-GNVDE,0,0,0,0.264057,1,0,1,0,1,...,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0
2,3668-QPYBK,0,0,0,-1.066498,1,0,1,1,0,...,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1
3,7795-CFOCW,0,0,0,0.721435,0,0,1,0,1,...,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0
4,9237-HQITU,0,0,0,-1.066498,1,0,0,0,0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10343,7623-TRNQN,0,0,1,-1.108078,1,0,0,0,0,...,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1
10344,8580-AECUZ,1,0,0,-1.108078,1,0,0,0,0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1
10345,0661-XEYAN,1,0,0,-1.108078,0,0,0,0,0,...,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1
10346,0362-ZBZWJ,0,0,0,0.347217,1,1,0,0,0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1
10347,5515-IDEJJ,0,1,1,-1.108078,1,0,0,0,0,...,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1